# Generated by Django 3.1.2 on 2021-03-23 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=100, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('url', models.CharField(default='url', max_length=500, verbose_name='链接')),
                ('thumbnail', models.CharField(default='thumbnail', max_length=500, verbose_name='简略图')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='VideoRecommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='推荐视频')),
            ],
            options={
                'verbose_name': '推荐视频',
                'verbose_name_plural': '推荐视频',
            },
        ),
    ]
