# Generated by Django 3.1.2 on 2021-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='暂无视频介绍', max_length=300, verbose_name='描述'),
        ),
    ]
