# Generated by Django 3.1.2 on 2021-04-19 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_auto_20210324_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
        migrations.AlterModelOptions(
            name='videorecommended',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
        migrations.AlterField(
            model_name='video',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='description', max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='thumbnail', max_length=500, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='time of updating'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='url', max_length=500, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='videorecommended',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='videorecommended',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='video'),
        ),
    ]
