# Generated by Django 3.1.2 on 2021-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='channelDescription',
            field=models.CharField(default=1, max_length=500, verbose_name='频道描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.CharField(default='', max_length=500, verbose_name='封面'),
        ),
    ]
