# Generated by Django 3.1.2 on 2021-04-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210324_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='', max_length=100, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='channelDescription',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.CharField(default='', max_length=500, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='nickname'),
        ),
    ]
